// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZj3m-15Ba7xWf6IEXRbEkUwmLu21-xDM',
    appId: '1:894408144984:web:e9a4c40a77430d1845b22d',
    messagingSenderId: '894408144984',
    projectId: 'spotify-minhtritt01',
    authDomain: 'spotify-minhtritt01.firebaseapp.com',
    storageBucket: 'spotify-minhtritt01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnXwkSA0liElTIXZNpqrk--oc4jD5JCCs',
    appId: '1:894408144984:android:5e04a5c9d6301be045b22d',
    messagingSenderId: '894408144984',
    projectId: 'spotify-minhtritt01',
    storageBucket: 'spotify-minhtritt01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpSO6yscu9NWEyrjSqFFD8pBnNfFMjs0I',
    appId: '1:894408144984:ios:0006c4ffe03077b045b22d',
    messagingSenderId: '894408144984',
    projectId: 'spotify-minhtritt01',
    storageBucket: 'spotify-minhtritt01.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpSO6yscu9NWEyrjSqFFD8pBnNfFMjs0I',
    appId: '1:894408144984:ios:0006c4ffe03077b045b22d',
    messagingSenderId: '894408144984',
    projectId: 'spotify-minhtritt01',
    storageBucket: 'spotify-minhtritt01.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZj3m-15Ba7xWf6IEXRbEkUwmLu21-xDM',
    appId: '1:894408144984:web:e37d259b265b1b3645b22d',
    messagingSenderId: '894408144984',
    projectId: 'spotify-minhtritt01',
    authDomain: 'spotify-minhtritt01.firebaseapp.com',
    storageBucket: 'spotify-minhtritt01.appspot.com',
  );
}
